
#Gameplay Settings
[gameplay]
	#Enables the progression system for the Codex.
	#If true, players must unlock entries via gameplay.
	#If false, all entries are visible by default.
	enableCodexProgression = true
	#Codex updating rate, specified in seconds
	#Range: 1.0 ~ 10000.0
	codexUpdateInterval = 3.0
	#Food spoiling on entering Valoria dimension
	enableFoodRot = true
	#Food spoiling time, specified in seconds
	#Range: 0.1 ~ 10000.0
	foodRotInterval = 3.0
	#Nihility System in Valoria
	enableNihility = true
	#Damage multiplier per 10% of excess Nihility
	#Formula: 1.0 + (segments * multiplier)
	#Range: 0.0 ~ 100.0
	nihilityDamageMultiplier = 2.0
	#Nihility applying time, specified in seconds
	#Range: 0.1 ~ 10000.0
	nihilityAccumulationInterval = 3.0
	#Nihility decreasing time, specified in seconds
	#Range: 0.1 ~ 10000.0
	nihilityDecayInterval = 6.0
	#Action on maximum Nihility amount reached
	#Allowed Values: KILL, DAMAGE, TELEPORT
	maxNihilityAction = "KILL"
	#Blindness on critical Nihility amount reached
	criticalNihilityBlindness = true

#Level Generation
[levelgen]
	#Pots spawn chance
	#Range: 0.0 ~ 1.0
	PotSpawnChance = 0.025

