
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "1395973880698503220"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = true
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 26

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[init.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Otherworld is loading"
		#The second line of text under the app name
		state = "Game Starting..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["loading"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["mclogo"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "Loading {{game.mods}} mods for Otherworld"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
        #List of buttons (max 2) to show on the RPC
                [[init.presence.buttons]]
                    label = "Otherworld Wiki"
                    url = "https://otherworld.wiki/"
        
                [[init.presence.buttons]]
                    label = "Discord"
                    url = "https://lunapixel.studio/discord"


#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[main_menu.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}}"
		#The second line of text under the app name
		state = "In the main menu"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
        #List of buttons (max 2) to show on the RPC
                [[main_menu.presence.buttons]]
                    label = "Otherworld Wiki"
                    url = "https://otherworld.wiki/"
        
                [[main_menu.presence.buttons]]
                    label = "Discord"
                    url = "https://lunapixel.studio/discord"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[server_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}}"
		#The second line of text under the app name
		state = "Scouring the ancient archives for a server"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = false

	#List of RPCs that will be displayed at random
	[[realms_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}}"
		#The second line of text under the app name
		state = "Browsing Realms"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[join_game.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}}"
		#The second line of text under the app name
		state = "Preparing for a grand adventure"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[single_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Adventuring in {{world.name}}"
		#The second line of text under the app name
		state = "Bravely forging ahead alone."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[multi_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Exploring the world of {{server.name}}"
		#The second line of text under the app name
		state = "With {{server.players.count}} others"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = false

	#List of RPCs that will be displayed at random
	[[realms.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on {{realm.name}}"
		#The second line of text under the app name
		state = "Playing on a Realm"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[paused.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Paused"
		#The second line of text under the app name
		state = "Taking a Brief Rest"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Fallback event for disabled events
[generic]

	#List of RPCs that will be displayed at random
	[[generic.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing Otherworld"
		#The second line of text under the app name
		state = "Up to Something Mysterious"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["menu"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Otherworld, for Forge {{game.version}}"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{game.mods}} mods installed"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "Exploring the Overworld"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["menu"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "Otherworld, for Forge {{game.version}}"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{game.mods}} mods installed"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "Facing the heat of The Nether"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["menu"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "Otherworld, for Forge {{game.version}}"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{game.mods}} mods installed"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "In the infinite void of The End"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["menu"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "Otherworld, for Forge {{game.version}}"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["{{images.player}}"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}}"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

