#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=curio;size=0", "id=feet;size=0", "id=hands;size=1", "id=charm;size=1", "id=talent;size=1", "id=bracelet;size=1"]

