#[选项]是否居中
option_in_center = false
#是否开启[背景框]
enable_background = false
#使用[渐变背景框]或[边框背景框]
faded_background = true
#是否绘制[回答]的背景
enable_ans_background = true
#是否绘制[选项]的背景
enable_opt_background = true
#剧情对话是否使用[打字机效果]
enable_typewriter_effect = true
#[打字机效果]打字速度
#Range: > 1
typewriter_effect_speed = 2
#[打字机效果]打字间隔
#Range: > 1
typewriter_effect_interval = 2

