
["Spawn Biome Utility Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#generateReport
	generateReport = true
	#suppressMinecraftMobReporting
	suppressMinecraftMobReporting = false
	#fixEmptyNether
	fixEmptyNether = true
	#Use the 'BiomeMobWeight.csv' file to balance Biome spawn values
	balanceBiomeSpawnValues = true
	#Fix min, max values and add nether creatures
	fixSpawnValues = true
	#Use the 'StructMobWeight.csv' file to balance structure spawn values
	balanceStructureSpawnValues = true
	#Mod Name set separated by SemiColons of mods to report.
	includedReportModsSet = "exampleModName;"

["Spawn Placement Fixes"]
	#Add mobs spawning in the air and falling to this list .
	defaultSpawnWeightList = ""

["Spawn Weight Values"]
	#minimum Spawn Weight
	#Range: 1 ~ 1000
	minSpawnWeight = 1
	#maximum Spawn Weight
	#Range: 1 ~ 1000
	maxSpawnWeight = 10
	#list of Mod:MobName,DefaultSpawnweight;
	defaultSpawnWeightList = "irons_spellbooks:necromancer,1;the_awakening_of_the_elder_souls:golden_zombie,1;the_awakening_of_the_elder_souls:golden_creeper,1;the_awakening_of_the_elder_souls:golden_witch,1;realmrpg_demons:chort,1;eidolon:wraith,1;eidolon:zombie_brute,1;eidolon:raven,1;eidolon:slimy_slug,1;eidolon:giant_skeleton,1;"

