# Don't change this! Version used to track needed updates.
version = 0

[lootInformationControl]
loot_information_status = "ONLY_NAME_IN_NAMETAG"
showInfoForAllItem = true

[rarity]
showRarityFor = "ALL"

[nameTag]
render_name_tag_on_look = true
add_text_border = true
render_stack_count = false
name_tag_look_sensitivity = 0.05
name_tag_text_alpha = 1.0
name_tag_background_alpha = 0.9945313
name_tag_scale = 0.5
name_tag_y_offset = 0.5

[tooltips]
render_tooltips_on_crouch = true